[workspace]
members = ["crates/rm-display-*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MPL-2.0"

[workspace.dependencies]
bytes = "1.6"
crc32fast = "1.4"
flate2 = "1.0"
prost = "0.12.6"
prost-build = "0.12.6"
thiserror = "1.0"
zstd = "0.13.3"
